// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 17.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace JiraTesterProService.OutputTemplate
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "C:\SourceCode\JiraTesterPro\src\JiraTesterProService\OutputTemplate\JiraTestOutput.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "17.0.0.0")]
    public partial class JiraTestOutput : JiraTestOutputBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public virtual string TransformText()
        {
            this.Write("<!DOCTYPE html><html languate=\"en\">\r\n");
            
            #line 8 "C:\SourceCode\JiraTesterPro\src\JiraTesterProService\OutputTemplate\JiraTestOutput.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.Header));
            
            #line default
            #line hidden
            this.Write("\r\n<body>\r\n<div class=\"container-fluid\">\r\n");
            
            #line 11 "C:\SourceCode\JiraTesterPro\src\JiraTesterProService\OutputTemplate\JiraTestOutput.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.HeaderSection));
            
            #line default
            #line hidden
            this.Write("\r\n\r\n");
            
            #line 13 "C:\SourceCode\JiraTesterPro\src\JiraTesterProService\OutputTemplate\JiraTestOutput.tt"
foreach(var testresult in Model.TestResult){
            
            #line default
            #line hidden
            this.Write("<div class=\"row\">\r\n<div class=\"col-sm border rounded\">\r\n<div class=\"table-respons" +
                    "ive\">\r\n<table class=\"table table-hover\"><caption>");
            
            #line 17 "C:\SourceCode\JiraTesterPro\src\JiraTesterProService\OutputTemplate\JiraTestOutput.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(testresult.Key));
            
            #line default
            #line hidden
            this.Write(@" </caption>
<thead class=""thead-light"">
<tr>
<th>StepId</th>
<th>Project</th>
<th>IssueType</th>
<th>ExecutedScenario</th>
<th>Create/Update</th>
<th>Action</th>
<th>Expected Status</th>
<th>Actual Status</th>
<th>WorkFlow Pass/Fail</th>
<th>ScreenTest Pass/Fail</th>
<th>WorkFlow Screen Value Pass/Fail</th>
<th>IssueKey</th>

<th>ScreenShots</th>

<th>Comments</th>
</tr> 
</thead>
<tbody>
");
            
            #line 39 "C:\SourceCode\JiraTesterPro\src\JiraTesterProService\OutputTemplate\JiraTestOutput.tt"
foreach(var result in Model.TestResult[testresult.Key]){
if (result.TestPassed){
            
            #line default
            #line hidden
            this.Write("<tr class=\"table-success\">\r\n");
            
            #line 42 "C:\SourceCode\JiraTesterPro\src\JiraTesterProService\OutputTemplate\JiraTestOutput.tt"
}
            
            #line default
            #line hidden
            
            #line 43 "C:\SourceCode\JiraTesterPro\src\JiraTesterProService\OutputTemplate\JiraTestOutput.tt"
else{
            
            #line default
            #line hidden
            this.Write("<tr class=\"table-danger\">\r\n");
            
            #line 45 "C:\SourceCode\JiraTesterPro\src\JiraTesterProService\OutputTemplate\JiraTestOutput.tt"
}
            
            #line default
            #line hidden
            this.Write("<td>");
            
            #line 46 "C:\SourceCode\JiraTesterPro\src\JiraTesterProService\OutputTemplate\JiraTestOutput.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(result.JiraTestMasterDto.StepId));
            
            #line default
            #line hidden
            this.Write("</td>\r\n<td>");
            
            #line 47 "C:\SourceCode\JiraTesterPro\src\JiraTesterProService\OutputTemplate\JiraTestOutput.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(result.ProjectName.GetEmptyIfEmptyOrNull()));
            
            #line default
            #line hidden
            this.Write("</td>\r\n<td>");
            
            #line 48 "C:\SourceCode\JiraTesterPro\src\JiraTesterProService\OutputTemplate\JiraTestOutput.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(result.JiraTestMasterDto?.IssueType.GetEmptyIfEmptyOrNull()));
            
            #line default
            #line hidden
            this.Write("</td>\r\n\r\n\r\n<td>\r\n");
            
            #line 52 "C:\SourceCode\JiraTesterPro\src\JiraTesterProService\OutputTemplate\JiraTestOutput.tt"
if (!string.IsNullOrEmpty(result.InputScreenFileName)){
            
            #line default
            #line hidden
            
            #line 53 "C:\SourceCode\JiraTesterPro\src\JiraTesterProService\OutputTemplate\JiraTestOutput.tt"
if (Model.IsIndividual){
            
            #line default
            #line hidden
            this.Write("<a href=\"");
            
            #line 54 "C:\SourceCode\JiraTesterPro\src\JiraTesterProService\OutputTemplate\JiraTestOutput.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(result.InputScreenFileName));
            
            #line default
            #line hidden
            this.Write("\">");
            
            #line 54 "C:\SourceCode\JiraTesterPro\src\JiraTesterProService\OutputTemplate\JiraTestOutput.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(result.JiraTestMasterDto?.Scenario.GetEmptyIfEmptyOrNull()));
            
            #line default
            #line hidden
            this.Write("</a>\r\n");
            
            #line 55 "C:\SourceCode\JiraTesterPro\src\JiraTesterProService\OutputTemplate\JiraTestOutput.tt"
}else {
            
            #line default
            #line hidden
            this.Write("<a href=\"");
            
            #line 56 "C:\SourceCode\JiraTesterPro\src\JiraTesterProService\OutputTemplate\JiraTestOutput.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(testresult.Key));
            
            #line default
            #line hidden
            this.Write("/");
            
            #line 56 "C:\SourceCode\JiraTesterPro\src\JiraTesterProService\OutputTemplate\JiraTestOutput.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(result.InputScreenFileName));
            
            #line default
            #line hidden
            this.Write("\">");
            
            #line 56 "C:\SourceCode\JiraTesterPro\src\JiraTesterProService\OutputTemplate\JiraTestOutput.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(result.JiraTestMasterDto?.Scenario.GetEmptyIfEmptyOrNull()));
            
            #line default
            #line hidden
            this.Write("</a>\r\n");
            
            #line 57 "C:\SourceCode\JiraTesterPro\src\JiraTesterProService\OutputTemplate\JiraTestOutput.tt"
}} else{
            
            #line default
            #line hidden
            
            #line 58 "C:\SourceCode\JiraTesterPro\src\JiraTesterProService\OutputTemplate\JiraTestOutput.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(result.JiraTestMasterDto?.Scenario.GetEmptyIfEmptyOrNull()));
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 59 "C:\SourceCode\JiraTesterPro\src\JiraTesterProService\OutputTemplate\JiraTestOutput.tt"
}
            
            #line default
            #line hidden
            this.Write("</td>\r\n\r\n\r\n\r\n\r\n<td>");
            
            #line 65 "C:\SourceCode\JiraTesterPro\src\JiraTesterProService\OutputTemplate\JiraTestOutput.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(result.JiraTestMasterDto?.Action.GetEmptyIfEmptyOrNull()));
            
            #line default
            #line hidden
            this.Write("</td>\r\n<td>");
            
            #line 66 "C:\SourceCode\JiraTesterPro\src\JiraTesterProService\OutputTemplate\JiraTestOutput.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(result.JiraTestMasterDto?.Status.GetEmptyIfEmptyOrNull()));
            
            #line default
            #line hidden
            this.Write("</td>\r\n<td>");
            
            #line 67 "C:\SourceCode\JiraTesterPro\src\JiraTesterProService\OutputTemplate\JiraTestOutput.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(result.JiraTestMasterDto?.ExpectedStatus.GetEmptyIfEmptyOrNull()));
            
            #line default
            #line hidden
            this.Write("</td>\r\n\r\n<td>\r\n\t\r\n\t");
            
            #line 71 "C:\SourceCode\JiraTesterPro\src\JiraTesterProService\OutputTemplate\JiraTestOutput.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(JiraOutPutExtension.GetJiraStatus(result)));
            
            #line default
            #line hidden
            this.Write("\r\n</td>\r\n\r\n<td>\r\n");
            
            #line 75 "C:\SourceCode\JiraTesterPro\src\JiraTesterProService\OutputTemplate\JiraTestOutput.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(result.TestStatus.GetEmptyIfEmptyOrNull()));
            
            #line default
            #line hidden
            this.Write("\r\n</td>\r\n\r\n");
            
            #line 78 "C:\SourceCode\JiraTesterPro\src\JiraTesterProService\OutputTemplate\JiraTestOutput.tt"
if (result.FailedScreenTestResultStatus){
            
            #line default
            #line hidden
            this.Write("<td><span class=\"badge bg-danger\">\r\n");
            
            #line 80 "C:\SourceCode\JiraTesterPro\src\JiraTesterProService\OutputTemplate\JiraTestOutput.tt"
}
            
            #line default
            #line hidden
            
            #line 81 "C:\SourceCode\JiraTesterPro\src\JiraTesterProService\OutputTemplate\JiraTestOutput.tt"
else{
            
            #line default
            #line hidden
            this.Write("<td><span>\r\n");
            
            #line 83 "C:\SourceCode\JiraTesterPro\src\JiraTesterProService\OutputTemplate\JiraTestOutput.tt"
}
            
            #line default
            #line hidden
            
            #line 84 "C:\SourceCode\JiraTesterPro\src\JiraTesterProService\OutputTemplate\JiraTestOutput.tt"
if (Model.IsIndividual){
            
            #line default
            #line hidden
            this.Write("<a href=\"ScreenTestResult.html\" \r\n");
            
            #line 86 "C:\SourceCode\JiraTesterPro\src\JiraTesterProService\OutputTemplate\JiraTestOutput.tt"
if(result.FailedScreenTestResultStatus){
            
            #line default
            #line hidden
            this.Write("class=\"text-white\"\r\n");
            
            #line 88 "C:\SourceCode\JiraTesterPro\src\JiraTesterProService\OutputTemplate\JiraTestOutput.tt"
}
            
            #line default
            #line hidden
            this.Write(">");
            
            #line 89 "C:\SourceCode\JiraTesterPro\src\JiraTesterProService\OutputTemplate\JiraTestOutput.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(result.ScreenTestStatus.GetEmptyIfEmptyOrNull()));
            
            #line default
            #line hidden
            this.Write("</a>\r\n");
            
            #line 90 "C:\SourceCode\JiraTesterPro\src\JiraTesterProService\OutputTemplate\JiraTestOutput.tt"
}else {
            
            #line default
            #line hidden
            this.Write("<a href=\"");
            
            #line 91 "C:\SourceCode\JiraTesterPro\src\JiraTesterProService\OutputTemplate\JiraTestOutput.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(testresult.Key));
            
            #line default
            #line hidden
            this.Write("/ScreenTestResult.html\"\r\n");
            
            #line 92 "C:\SourceCode\JiraTesterPro\src\JiraTesterProService\OutputTemplate\JiraTestOutput.tt"
if(result.FailedScreenTestResultStatus){
            
            #line default
            #line hidden
            this.Write("class=\"text-white\"\r\n");
            
            #line 94 "C:\SourceCode\JiraTesterPro\src\JiraTesterProService\OutputTemplate\JiraTestOutput.tt"
}
            
            #line default
            #line hidden
            this.Write(">");
            
            #line 95 "C:\SourceCode\JiraTesterPro\src\JiraTesterProService\OutputTemplate\JiraTestOutput.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(result.ScreenTestStatus.GetEmptyIfEmptyOrNull()));
            
            #line default
            #line hidden
            this.Write("</a>\r\n");
            
            #line 96 "C:\SourceCode\JiraTesterPro\src\JiraTesterProService\OutputTemplate\JiraTestOutput.tt"
}
            
            #line default
            #line hidden
            this.Write("</span>\r\n</td>\r\n\r\n\r\n\r\n<td>\r\n");
            
            #line 103 "C:\SourceCode\JiraTesterPro\src\JiraTesterProService\OutputTemplate\JiraTestOutput.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(JiraOutPutExtension.GetInValidValue(result)));
            
            #line default
            #line hidden
            this.Write("\r\n</td>\r\n<td>\r\n");
            
            #line 106 "C:\SourceCode\JiraTesterPro\src\JiraTesterProService\OutputTemplate\JiraTestOutput.tt"
if (result.JiraIssue!=null){
            
            #line default
            #line hidden
            this.Write("<a href=\"");
            
            #line 107 "C:\SourceCode\JiraTesterPro\src\JiraTesterProService\OutputTemplate\JiraTestOutput.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(result.JiraIssueUrl.GetEmptyIfEmptyOrNull()));
            
            #line default
            #line hidden
            this.Write("\">");
            
            #line 107 "C:\SourceCode\JiraTesterPro\src\JiraTesterProService\OutputTemplate\JiraTestOutput.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(result.JiraIssue.Key));
            
            #line default
            #line hidden
            this.Write("</a>\r\n");
            
            #line 108 "C:\SourceCode\JiraTesterPro\src\JiraTesterProService\OutputTemplate\JiraTestOutput.tt"
}
            
            #line default
            #line hidden
            this.Write("</td>\r\n\r\n<td>\r\n");
            
            #line 112 "C:\SourceCode\JiraTesterPro\src\JiraTesterProService\OutputTemplate\JiraTestOutput.tt"
if (result.ScreenShotPath!=null){
            
            #line default
            #line hidden
            
            #line 113 "C:\SourceCode\JiraTesterPro\src\JiraTesterProService\OutputTemplate\JiraTestOutput.tt"
if (Model.IsIndividual){
            
            #line default
            #line hidden
            this.Write("<a href=\"");
            
            #line 114 "C:\SourceCode\JiraTesterPro\src\JiraTesterProService\OutputTemplate\JiraTestOutput.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(result.ScreenShotFileName));
            
            #line default
            #line hidden
            this.Write("\">");
            
            #line 114 "C:\SourceCode\JiraTesterPro\src\JiraTesterProService\OutputTemplate\JiraTestOutput.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(result.ScreenShotFileName));
            
            #line default
            #line hidden
            this.Write("</a>\r\n");
            
            #line 115 "C:\SourceCode\JiraTesterPro\src\JiraTesterProService\OutputTemplate\JiraTestOutput.tt"
}else {
            
            #line default
            #line hidden
            this.Write("<a href=\"");
            
            #line 116 "C:\SourceCode\JiraTesterPro\src\JiraTesterProService\OutputTemplate\JiraTestOutput.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(testresult.Key));
            
            #line default
            #line hidden
            this.Write("/");
            
            #line 116 "C:\SourceCode\JiraTesterPro\src\JiraTesterProService\OutputTemplate\JiraTestOutput.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(result.ScreenShotFileName));
            
            #line default
            #line hidden
            this.Write("\">");
            
            #line 116 "C:\SourceCode\JiraTesterPro\src\JiraTesterProService\OutputTemplate\JiraTestOutput.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(result.ScreenShotFileName));
            
            #line default
            #line hidden
            this.Write("</a>\r\n");
            
            #line 117 "C:\SourceCode\JiraTesterPro\src\JiraTesterProService\OutputTemplate\JiraTestOutput.tt"
}}
            
            #line default
            #line hidden
            this.Write("</td>\r\n\r\n\r\n\r\n\r\n<td>\r\n");
            
            #line 124 "C:\SourceCode\JiraTesterPro\src\JiraTesterProService\OutputTemplate\JiraTestOutput.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(result.Comment.GetEmptyIfEmptyOrNull()));
            
            #line default
            #line hidden
            this.Write("\r\n</td>\r\n");
            
            #line 126 "C:\SourceCode\JiraTesterPro\src\JiraTesterProService\OutputTemplate\JiraTestOutput.tt"
}
            
            #line default
            #line hidden
            this.Write("\r\n\r\n</tr>\r\n\r\n</tbody>\r\n\r\n</table>\r\n</div>\r\n</div>\r\n</div>\r\n\r\n\r\n\r\n</div>\r\n\r\n");
            
            #line 142 "C:\SourceCode\JiraTesterPro\src\JiraTesterProService\OutputTemplate\JiraTestOutput.tt"
}
            
            #line default
            #line hidden
            this.Write("\r\n</div>\r\n</body></html>");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
    #region Base class
    /// <summary>
    /// Base class for this transformation
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "17.0.0.0")]
    public class JiraTestOutputBase
    {
        #region Fields
        private global::System.Text.StringBuilder generationEnvironmentField;
        private global::System.CodeDom.Compiler.CompilerErrorCollection errorsField;
        private global::System.Collections.Generic.List<int> indentLengthsField;
        private string currentIndentField = "";
        private bool endsWithNewline;
        private global::System.Collections.Generic.IDictionary<string, object> sessionField;
        #endregion
        #region Properties
        /// <summary>
        /// The string builder that generation-time code is using to assemble generated output
        /// </summary>
        protected System.Text.StringBuilder GenerationEnvironment
        {
            get
            {
                if ((this.generationEnvironmentField == null))
                {
                    this.generationEnvironmentField = new global::System.Text.StringBuilder();
                }
                return this.generationEnvironmentField;
            }
            set
            {
                this.generationEnvironmentField = value;
            }
        }
        /// <summary>
        /// The error collection for the generation process
        /// </summary>
        public System.CodeDom.Compiler.CompilerErrorCollection Errors
        {
            get
            {
                if ((this.errorsField == null))
                {
                    this.errorsField = new global::System.CodeDom.Compiler.CompilerErrorCollection();
                }
                return this.errorsField;
            }
        }
        /// <summary>
        /// A list of the lengths of each indent that was added with PushIndent
        /// </summary>
        private System.Collections.Generic.List<int> indentLengths
        {
            get
            {
                if ((this.indentLengthsField == null))
                {
                    this.indentLengthsField = new global::System.Collections.Generic.List<int>();
                }
                return this.indentLengthsField;
            }
        }
        /// <summary>
        /// Gets the current indent we use when adding lines to the output
        /// </summary>
        public string CurrentIndent
        {
            get
            {
                return this.currentIndentField;
            }
        }
        /// <summary>
        /// Current transformation session
        /// </summary>
        public virtual global::System.Collections.Generic.IDictionary<string, object> Session
        {
            get
            {
                return this.sessionField;
            }
            set
            {
                this.sessionField = value;
            }
        }
        #endregion
        #region Transform-time helpers
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void Write(string textToAppend)
        {
            if (string.IsNullOrEmpty(textToAppend))
            {
                return;
            }
            // If we're starting off, or if the previous text ended with a newline,
            // we have to append the current indent first.
            if (((this.GenerationEnvironment.Length == 0) 
                        || this.endsWithNewline))
            {
                this.GenerationEnvironment.Append(this.currentIndentField);
                this.endsWithNewline = false;
            }
            // Check if the current text ends with a newline
            if (textToAppend.EndsWith(global::System.Environment.NewLine, global::System.StringComparison.CurrentCulture))
            {
                this.endsWithNewline = true;
            }
            // This is an optimization. If the current indent is "", then we don't have to do any
            // of the more complex stuff further down.
            if ((this.currentIndentField.Length == 0))
            {
                this.GenerationEnvironment.Append(textToAppend);
                return;
            }
            // Everywhere there is a newline in the text, add an indent after it
            textToAppend = textToAppend.Replace(global::System.Environment.NewLine, (global::System.Environment.NewLine + this.currentIndentField));
            // If the text ends with a newline, then we should strip off the indent added at the very end
            // because the appropriate indent will be added when the next time Write() is called
            if (this.endsWithNewline)
            {
                this.GenerationEnvironment.Append(textToAppend, 0, (textToAppend.Length - this.currentIndentField.Length));
            }
            else
            {
                this.GenerationEnvironment.Append(textToAppend);
            }
        }
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void WriteLine(string textToAppend)
        {
            this.Write(textToAppend);
            this.GenerationEnvironment.AppendLine();
            this.endsWithNewline = true;
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void Write(string format, params object[] args)
        {
            this.Write(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void WriteLine(string format, params object[] args)
        {
            this.WriteLine(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Raise an error
        /// </summary>
        public void Error(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Raise a warning
        /// </summary>
        public void Warning(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            error.IsWarning = true;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Increase the indent
        /// </summary>
        public void PushIndent(string indent)
        {
            if ((indent == null))
            {
                throw new global::System.ArgumentNullException("indent");
            }
            this.currentIndentField = (this.currentIndentField + indent);
            this.indentLengths.Add(indent.Length);
        }
        /// <summary>
        /// Remove the last indent that was added with PushIndent
        /// </summary>
        public string PopIndent()
        {
            string returnValue = "";
            if ((this.indentLengths.Count > 0))
            {
                int indentLength = this.indentLengths[(this.indentLengths.Count - 1)];
                this.indentLengths.RemoveAt((this.indentLengths.Count - 1));
                if ((indentLength > 0))
                {
                    returnValue = this.currentIndentField.Substring((this.currentIndentField.Length - indentLength));
                    this.currentIndentField = this.currentIndentField.Remove((this.currentIndentField.Length - indentLength));
                }
            }
            return returnValue;
        }
        /// <summary>
        /// Remove any indentation
        /// </summary>
        public void ClearIndent()
        {
            this.indentLengths.Clear();
            this.currentIndentField = "";
        }
        #endregion
        #region ToString Helpers
        /// <summary>
        /// Utility class to produce culture-oriented representation of an object as a string.
        /// </summary>
        public class ToStringInstanceHelper
        {
            private System.IFormatProvider formatProviderField  = global::System.Globalization.CultureInfo.InvariantCulture;
            /// <summary>
            /// Gets or sets format provider to be used by ToStringWithCulture method.
            /// </summary>
            public System.IFormatProvider FormatProvider
            {
                get
                {
                    return this.formatProviderField ;
                }
                set
                {
                    if ((value != null))
                    {
                        this.formatProviderField  = value;
                    }
                }
            }
            /// <summary>
            /// This is called from the compile/run appdomain to convert objects within an expression block to a string
            /// </summary>
            public string ToStringWithCulture(object objectToConvert)
            {
                if ((objectToConvert == null))
                {
                    throw new global::System.ArgumentNullException("objectToConvert");
                }
                System.Type t = objectToConvert.GetType();
                System.Reflection.MethodInfo method = t.GetMethod("ToString", new System.Type[] {
                            typeof(System.IFormatProvider)});
                if ((method == null))
                {
                    return objectToConvert.ToString();
                }
                else
                {
                    return ((string)(method.Invoke(objectToConvert, new object[] {
                                this.formatProviderField })));
                }
            }
        }
        private ToStringInstanceHelper toStringHelperField = new ToStringInstanceHelper();
        /// <summary>
        /// Helper to produce culture-oriented representation of an object as a string
        /// </summary>
        public ToStringInstanceHelper ToStringHelper
        {
            get
            {
                return this.toStringHelperField;
            }
        }
        #endregion
    }
    #endregion
}
